// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicidadDinamicaWeb.Data;

#nullable disable

namespace PublicidadDinamicaWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226054553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Anuncio", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAnuncio"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("TextoPromocional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAnuncio");

                    b.HasIndex("IdProducto");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Comercio", b =>
                {
                    b.Property<int>("IdComercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComercio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreComercio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdComercio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.ConfiguracionPublicidad", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AnimarPrecio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ColorFondo")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorPrecioBajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColorPrecioNormal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColorPrecioSubio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DuracionAnimacionMs")
                        .HasColumnType("int");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<string>("ImagenFondo")
                        .HasColumnType("longtext");

                    b.Property<bool>("MostrarBajo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MostrarPrecioAnterior")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MostrarSubio")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TiempoPorSlideMs")
                        .HasColumnType("int");

                    b.Property<string>("TipoAnimacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoFondo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("IdComercio");

                    b.ToTable("ConfiguracionPublicidad");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.HistorialPrecio", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioAnterior")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioNuevo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdProducto");

                    b.ToTable("HistorialPrecios");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioActual")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdComercio");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.PublicidadDinamicaWeb.Models.VersionPantalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VersionPantalla");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Anuncio", b =>
                {
                    b.HasOne("PublicidadDinamicaWeb.Models.Producto", "Producto")
                        .WithMany("Anuncios")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Comercio", b =>
                {
                    b.HasOne("PublicidadDinamicaWeb.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.ConfiguracionPublicidad", b =>
                {
                    b.HasOne("PublicidadDinamicaWeb.Models.Comercio", "Comercio")
                        .WithMany("Configuraciones")
                        .HasForeignKey("IdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.HistorialPrecio", b =>
                {
                    b.HasOne("PublicidadDinamicaWeb.Models.Producto", "Producto")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Producto", b =>
                {
                    b.HasOne("PublicidadDinamicaWeb.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicidadDinamicaWeb.Models.Comercio", "Comercio")
                        .WithMany("Productos")
                        .HasForeignKey("IdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.UsuarioRol", b =>
                {
                    b.HasOne("PublicidadDinamicaWeb.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicidadDinamicaWeb.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Comercio", b =>
                {
                    b.Navigation("Configuraciones");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Producto", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("HistorialPrecios");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("PublicidadDinamicaWeb.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
